raise Exception("error")
print("testings")