raise Exception("error")
print("testing")