raise Exception("error")
print("test")